Fix example_bigtable system test
VladaZakharova/airflow pull request #95
Opened 2024-08-23 13:12 UTC by olegkachur-e

Fix issues with bigtable system test:

- ensure correct id strings with proper length, as it might be issues depending on length of SYSTEM_TESTS_ENV_ID value.
- assign proper id values to resources used
- add constants for resources names limits

2024-08-26 09:51 UTC, VladaZakharova requested changes
Please, for the task calls please add comments like this 
`(
        #TEST SETUP
        [create_instance_task, create_instance_task2]
        >> create_tables()
        #TEST BODY
        >> wait_for_table_replication_task
        >> update_clusters_and_instance()
        #TEST TEARDOWN
        >> delete_table_task
        >> delete_table_task2
        >> [delete_instance_task, delete_instance_task2]
    )`

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +ENV_ID = os.environ.get("SYSTEM_TESTS_ENV_ID").lower().replace('_', '-')
this line is okay, you don't need to change the content of this variable itself. In every place this stirng is used you can add only 'replace()', without 'lower()'

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +ENV_ID = os.environ.get("SYSTEM_TESTS_ENV_ID").lower().replace('_', '-')
```suggestion
ENV_ID = os.environ.get("SYSTEM_TESTS_ENV_ID")
```

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +DAG_ID = f"bigtable"
I think we don't need f-string here
```suggestion
DAG_ID = "bigtable"
```

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
>  CBT_INSTANCE_DISPLAY_NAME = "Instance-name"
```suggestion
CBT_INSTANCE_DISPLAY_NAME = "instance-name"
```

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +CB_INSTANCE_ID_BASE = (
I am afraid it is hard to understand how the name will look like :)

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
>  CBT_INSTANCE_DISPLAY_NAME_UPDATED = f"{CBT_INSTANCE_DISPLAY_NAME} - updated"
```suggestion
CBT_INSTANCE_DISPLAY_NAME_UPDATED = f"{CBT_INSTANCE_DISPLAY_NAME}-updated"
```

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +)
```suggestion
).replace("_", "-")
```
or vise versa, not sure which format should be here

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +CBT_CLUSTER_ID = f"cluster-id-"
Do we need f-string here?

2024-08-26 09:51 UTC, VladaZakharova commented on tests/system/providers/google/cloud/bigtable/example_bigtable.py
> +CBT_TABLE_ID = f"bigtable-table-id-"
Do we need f-string here?

2024-09-13 12:28 UTC, moiseenkov approved these changes
Changes look good and the system test is green on staging.

2024-09-16 10:25 UTC, olegkachur-e commented
Closing as ready for the community

2024-09-16 10:25 UTC, closed without merging